### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by valec4** [nectR-Tutoring/nectr-vagrant#1]
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0xb5d16074>
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/urls/resolvers.py", line 312, in url_patterns
    iter(patterns)
TypeError: 'module' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vagrant/.virtualenvs/nectr/lib/python3.4/site-packages/django/urls/resolvers.py", line 319, in url_patterns
    raise ImproperlyConfigured(msg.format(name=self.urlconf_name))
django.core.exceptions.ImproperlyConfigured: The included URLconf 'tutr_app.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import.

**Comment by ghost** [comment]
Test Comments

**Comment by ghost** [comment]
This happens becuase of the new version of nectR and the name changes. I will be rewriting the Vagrantfile to pull down for the nectr-docker or nectr repo and run build there.
